version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    # Base jlesage/baseimage-gui + zulu8-jdk acompanhados aqui
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
