name: release

on:
  push:
    branches: [main, master, "ci/*", "port/*"]
    tags: ["v*"]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/rezenderaul/idrac6
          tags: |
            type=raw,value=ci,enable=${{ startsWith(github.ref, 'refs/heads/ci/') || startsWith(github.ref, 'refs/heads/port/') }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short,enable={{is_default_branch}}
            type=ref,event=tag
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
